### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by LadyLivathee** [jebbyk/OSBES-minecraft-bedrock-edition-shader#82]
I don't see any features that are functioning and each block is blue and black, same with with the water. I'm new to texture packs I'm not sure what I am doing wrong. I have tried it with another mod, and several times without any other mods and still get this issue.

![Screenshot (17)](https://user-images.githubusercontent.com/79952848/109743411-7fcde980-7b85-11eb-89bc-73e69b193d2e.png)

**Comment by jebbyk** [comment]
I'm not sure it is related to OSBES somehow. I think it is something wrong with your instalation. Please try to reinstall minecraft. Maybe it will help

**Comment by jibanyanlnewels** [comment]
I've been having the same problem, i believe it is something to do with windows 10 edition, as i have been using 1.16.40 and have been having the same problem with these shaders for quite a while now, i believe the problem is glsl shaders don't work on windows 10 edition, as windows 10 edition uses dx 11 hlsl shaders

**Comment by jebbyk** [comment]
ahh, ye ofc it will not work on windows 10
